name: Running tests prior to build stage.

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run tests and merge into staging
        run: |
          echo "ok"
          ls -al
          echo "ok2"
          git checkout ${GITHUB_REF#refs/heads/}
          ls -al
      - name: test2
        run: |
          git rebase origin/staging
          git branch staging
          git push origin staging:staging
          git push origin :${GITHUB_REF#refs/heads/}
