name: Running tests prior to build stage.

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Branch name
        run: echo running on branch ${GITHUB_REF##*/}
      - name: test
        run: git fetch
      - name: Push to build stage
        run: |
          git checkout ${GITHUB_REF#refs/heads/}
          git rebase origin/staging
          git branch staging
          git push origin staging:staging
          git push origin :${GITHUB_REF#refs/heads/}
