name: Running tests prior to build stage.

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests and merge into staging
        run: |
          git checkout dev
          git push origin dev:staging
          
