name: Running tests prior to build stage.

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests and merge into staging
        run: |
          git log --graph --decorate --pretty=oneline --abbrev-commit
          git rebase origin/staging
          git branch staging
          git push origin staging:staging
          git push origin :${GITHUB_REF#refs/heads/}
          
